fix: Update NVM installation script syntax

diff --git a/Jenkinsfile.test b/Jenkinsfile.test
--- a/Jenkinsfile.test
+++ b/Jenkinsfile.test
@@ -52,9 +52,14 @@ pipeline {
                         sh '''
                             curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
                             export NVM_DIR="$HOME/.nvm"
-                            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-                            nvm install ${NODE_VERSION}
-                            nvm use ${NODE_VERSION}
+                            if [ -f "$NVM_DIR/nvm.sh" ]; then
+                                . "$NVM_DIR/nvm.sh"
+                                nvm install ${NODE_VERSION}
+                                nvm use ${NODE_VERSION}
+                            else
+                                echo "NVM installation failed"
+                                exit 1
+                            fi
                         '''
                     }
                 }
